[[CUTENSOR]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "20d934d13d0f5aa6b7484c09f8c252ad32005bcd"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR.download]]
    sha256 = "130f3e9fce6907d49a9401a9dfc3320fa35588f1162b40bb2be4f75723ce230a"
    url = "https://github.com/maleadt/CUTENSOR_jll.jl/releases/download/CUTENSOR-v1.4.0+1/CUTENSOR.v1.4.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
